// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpySa23RF6ywfN0i5qAqgxE-PkX36zgFw',
    appId: '1:787053033101:web:6fc2d9430f2454345714c4',
    messagingSenderId: '787053033101',
    projectId: 'raahee-global-library-84037',
    authDomain: 'raahee-global-library-84037.firebaseapp.com',
    storageBucket: 'raahee-global-library-84037.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtITPUtB7nAsRZOXiMw-ioymrulFMkoc',
    appId: '1:787053033101:android:92c507d875a29de25714c4',
    messagingSenderId: '787053033101',
    projectId: 'raahee-global-library-84037',
    storageBucket: 'raahee-global-library-84037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdT_tdn81hXVKvtp_nAmKKSrHKvw7nsuI',
    appId: '1:787053033101:ios:7d46425a85ba902f5714c4',
    messagingSenderId: '787053033101',
    projectId: 'raahee-global-library-84037',
    storageBucket: 'raahee-global-library-84037.firebasestorage.app',
    iosBundleId: 'com.raahee.globalLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdT_tdn81hXVKvtp_nAmKKSrHKvw7nsuI',
    appId: '1:787053033101:ios:d6f4a10e24b0e6135714c4',
    messagingSenderId: '787053033101',
    projectId: 'raahee-global-library-84037',
    storageBucket: 'raahee-global-library-84037.firebasestorage.app',
    iosBundleId: 'com.example.raaheeGlobalBookLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpySa23RF6ywfN0i5qAqgxE-PkX36zgFw',
    appId: '1:787053033101:web:e7252adc8fb0c7735714c4',
    messagingSenderId: '787053033101',
    projectId: 'raahee-global-library-84037',
    authDomain: 'raahee-global-library-84037.firebaseapp.com',
    storageBucket: 'raahee-global-library-84037.firebasestorage.app',
  );

}